spring:
  application:
    name: enterprise-config

  profiles:
    active: prod

database:
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:5432}
  username: ${DB_USERNAME:postgres}
  password: ${DB_PASSWORD:password}

mail:
  enabled: true
  host: smtp.gmail.com
  port: 587

features:
  attendance: true
  direct-selling: true
  loyalty: false

sales:
  route:
    max-outlet-per-route: 250